# Generated by Django 3.0.8 on 2021-01-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='PlayerDetails',
        ),
    ]
