# Generated by Django 3.0.8 on 2021-01-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20210120_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetails',
            name='country',
            field=models.CharField(default='UK', max_length=60),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='league_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='player_age',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='player_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='position',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='team_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
