# Generated by Django 3.0.8 on 2021-01-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20210121_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetails',
            name='league_name',
            field=models.CharField(default='EPL', max_length=60),
        ),
    ]
